name: project_par_fans
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter_launcher_icons: "^0.14.2"
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.8
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  firebase_database: 
  firebase_storage: 

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/user_placeholder.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"