name: project_par_fans
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  firebase_database: 
  firebase_storage: 

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

