name: project_par_fans
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  firebase_core: 
  firebase_auth: 
  firebase_database: 
  firebase_storage: 
  cloud_firestore: 

flutter:
  uses-material-design: true
  assets:
    - assets/parfans_logo.png
    - assets/parfans_logo.jpg

