// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaPQj_43CYjMSHP_VcL-X5kr4-3iWFTaU',
    appId: '1:978701716541:web:8f08880f1f9a387f156e54',
    messagingSenderId: '978701716541',
    projectId: 'par-fans',
    authDomain: 'par-fans.firebaseapp.com',
    storageBucket: 'par-fans.firebasestorage.app',
    measurementId: 'G-31KBY8ERYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV5RW4Wqc_UZ9dT0sC7PwIWwZp0EjgOCE',
    appId: '1:978701716541:android:a93ea09675e1fef7156e54',
    messagingSenderId: '978701716541',
    projectId: 'par-fans',
    storageBucket: 'par-fans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk8I3RrDiU-LG2zi7xjjWVO1JUmZHtFEA',
    appId: '1:978701716541:ios:935859b625529241156e54',
    messagingSenderId: '978701716541',
    projectId: 'par-fans',
    storageBucket: 'par-fans.firebasestorage.app',
    iosBundleId: 'com.example.projectParFans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk8I3RrDiU-LG2zi7xjjWVO1JUmZHtFEA',
    appId: '1:978701716541:ios:935859b625529241156e54',
    messagingSenderId: '978701716541',
    projectId: 'par-fans',
    storageBucket: 'par-fans.firebasestorage.app',
    iosBundleId: 'com.example.projectParFans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaPQj_43CYjMSHP_VcL-X5kr4-3iWFTaU',
    appId: '1:978701716541:web:b79949d0a43e6af7156e54',
    messagingSenderId: '978701716541',
    projectId: 'par-fans',
    authDomain: 'par-fans.firebaseapp.com',
    storageBucket: 'par-fans.firebasestorage.app',
    measurementId: 'G-EHHJEG1KDG',
  );
}
